// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUiEpgtO-QTQkPlmZZWo5PjKxLIIpObSY',
    appId: '1:350214027826:web:89e8132e53b316ae275a2b',
    messagingSenderId: '350214027826',
    projectId: 'stump-vision-7ee09',
    authDomain: 'stump-vision-7ee09.firebaseapp.com',
    storageBucket: 'stump-vision-7ee09.firebasestorage.app',
    measurementId: 'G-WGWCK9L99B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXTYdV9zCXeLTVXn7UI3TA9TOfoB2gPI',
    appId: '1:350214027826:android:fb3fa63b3ec77292275a2b',
    messagingSenderId: '350214027826',
    projectId: 'stump-vision-7ee09',
    storageBucket: 'stump-vision-7ee09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgWCRIsojI4rNMas-LPKfbnVruYOy954k',
    appId: '1:350214027826:ios:37ac0397e41c3ee7275a2b',
    messagingSenderId: '350214027826',
    projectId: 'stump-vision-7ee09',
    storageBucket: 'stump-vision-7ee09.firebasestorage.app',
    iosBundleId: 'com.example.stumpVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgWCRIsojI4rNMas-LPKfbnVruYOy954k',
    appId: '1:350214027826:ios:37ac0397e41c3ee7275a2b',
    messagingSenderId: '350214027826',
    projectId: 'stump-vision-7ee09',
    storageBucket: 'stump-vision-7ee09.firebasestorage.app',
    iosBundleId: 'com.example.stumpVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUiEpgtO-QTQkPlmZZWo5PjKxLIIpObSY',
    appId: '1:350214027826:web:49a6812ba3e2d4c9275a2b',
    messagingSenderId: '350214027826',
    projectId: 'stump-vision-7ee09',
    authDomain: 'stump-vision-7ee09.firebaseapp.com',
    storageBucket: 'stump-vision-7ee09.firebasestorage.app',
    measurementId: 'G-1XRRT7P8Z1',
  );
}
